### ISSUE TITLE
low depth and fluctuating eval : why ?

### ISSUE THREAD

**Issue by tissatussa** [EngineProgramming/honse#12]
recently i played Black against the newest Honse, using CuteChess GUI (on Linux). After the game (15 minutes per player) i was wondering how Honse would have played with the Black pieces in a certain position. From this analysis i got some questions about the evaluation of Honse, maybe it can help you developing it .. or give some explanation for its output.

here's the game notation upto move 15, plus a game animation to quickly see the arising complications. At move 15 you see a typical position where Black had a clear advantage and several winning moves.

![Honse-vs-RB-X2FgFFlB](https://user-images.githubusercontent.com/1109281/234266161-a9bacb7e-5deb-4ef3-a045-ca6ad4284baf.gif)

```
[Event "human vs engine"]
[Site "Holland @ https://lichess.org/anCeLoCT/black "]
[Date "2023.04.23"]
[Round "?"]
[White "Honse"]
[Black "Roelof Berkepeis"]
[Result "0-1"]
[ECO "A40"]
[GameDuration "00:28:56"]
[Opening "Queen's pawn"]
[PlyCount "46"]
[TimeControl "900+3"]

 1.  d4      {-0.92/8 90s}      e6    {19s}
 2.  c3      {+0.95/7 82s}      f5    {14s}
 3.  e4      {+1.48/7 74s}      fxe4  {65s}
 4. Bc4      {-0.86/6 67s}     Nf6    {59s}
 5. Bg5      {+1.01/7 60s}      d5    {69s}
 6. Be2      {+1.13/7 55s}     Bd6    {70s}
 7. Na3      {-1.27/6 49s}      c6    {22s}
 8. Nc2      {-1.45/6 45s}     Nbd7   {42s}
 9. Nh3      {-1.53/6 41s}     O-O    {27s}
10. Ne3      {-1.88/6 37s}     Qe8    {56s}
11. Bf4      {-1.19/6 33s}      e5    {11s}
12. Bg5      {+0.29/7 30s}      exd4  {12s}
13. Nf5      {+0.68/7 28s}     Bc7     {8.0s}
14. Nxd4     {-2.23/6 25s}     Ne5    {18s}
15. O-O      {-2.93/6 23s}     ...
```

Afterwards i analysed the position after 15. O-O :

![position-black-to-move](https://user-images.githubusercontent.com/1109281/234266246-158ce82c-77c0-4191-bdc1-5c3b064ab242.png)

r1b1qrk1/ppb3pp/2p2n2/3pn1B1/3Np3/2P4N/PP2BPPP/R2Q1RK1 b - - 2 15
Black to move.

It's obvious that Black is much better and at this moment in the game Black should think how to start the attack on the White King : almost all Blacks pieces are optimal placed for an attack, only the Bc8 should develop and then even Ra8 can join the game .. several good moves exist and many tactical ideas, eg. moving the Ne5 will widen the scope of Bc7 even to h2 with check .. A chess player will smell blood now !

Black has many good moves but can only capture one piece : Nh3 is attacked by Bc8. Taking the kNight will probably result in a damaged pawn structure, but this implies a half open g-line, offering Rooks a way to attack .. on the short term, the damaged pawn structure is a tactical liability, on the long term those pawn can easily be captured.

Here are the top-5 eval results of the Stockfish 14 NNUE engine at LiChess-org :

![SF-eval](https://user-images.githubusercontent.com/1109281/234266311-57b312ca-c541-4eca-a000-517fa41a1973.png)

In the game i did Nfg4, a less favorable move (eval 3.3), but good enough to win that game : how rich chess is !

I also let Honse itself think about a good move for Black in the position. Here are the evaluation results of Honse at several depths, while thinking 'infinite' :

![Honse-eval](https://user-images.githubusercontent.com/1109281/234266341-71987efd-32c4-497b-b8ae-315b6a6206d6.png)

Indeed Honse finds Bxh3 best move, but the eval is far less than SF's .. and Bxh3 even was its first choice at depth 1 !?  Also Qg6 and h6 are in the SF list (which is our best reference nowadays, i think) .. depth 8 is reached after 04m32s -- reaching the next depth took more then 1 hour, so i stopped the calculations .. i was wondering how long it would take to reach depth 9, and if Bxh3 would still be best move and which eval .. it seems all evals at ODD depths are much higher, the eval clearly fluctuates .. why ?  And why doesn't Honse reach higher depths ?  Tactical positions like this require it !  A huge number of nodes are searched though ..

**Comment by 1337crisis** [comment]
Honse is very young in it's development, featuring only a very basic evaluation function and an even more simple search. The odd-even eval is likely due to Honse lacking quiescence search.

**Comment by tissatussa** [comment]
OK, so this info was no surprise for you ? Can it help to improve Honse ? At this moment i'm testing this position with other weak / simple engines .. Black can win in many ways, but it seems hard for those engines : they tend to let their advantage slip away move by move, and finally often lose !? (against 2700+) Chess is complicated..

**Comment by 1337crisis** [comment]
No I would say it's to be expected that the eval is very unstable with Honse. We're grateful that you're testing it and reporting your findings, but as I previously said, Honse is very early in development. It's elo is <<2000.
